"""updated product model

Revision ID: 3e443f46dd09
Revises: 36824b20f6e8
Create Date: 2024-11-07 08:50:49.112292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e443f46dd09'
down_revision = '36824b20f6e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('login')

    # ### end Alembic commands ###
