"""Add created_at column to transaction table

Revision ID: 4c03bf860812
Revises: df2515872bdc
Create Date: 2024-11-10 02:02:51.126167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c03bf860812'
down_revision = 'df2515872bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DEPOSIT', 'WITHDRAWAL', 'PURCHASE', name='transactiontype'),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=9), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.Enum('DEPOSIT', 'WITHDRAWAL', 'PURCHASE', name='transactiontype'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
